--- 
cwd: /home/waterlogged/public_html/waterlogged
log_file: log/mongrel.log
port: "8000"
environment: production
group: waterlogged
user: waterlogged
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 3
